# Generated by Django 6.0 on 2025-12-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=44)),
                ('client_name', models.CharField()),
                ('creation_date', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
