# Generated by Django 6.0 on 2025-12-12 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_client_id_alter_client_client_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='WgClient',
        ),
        migrations.CreateModel(
            name='WgStatsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.wgclient')),
            ],
        ),
    ]
