# Generated by Django 6.0 on 2025-12-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_client_wgclient_wgstatsrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='wgstatsrecord',
            name='allowed_ips',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wgstatsrecord',
            name='endpoint',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wgstatsrecord',
            name='latest_handshake',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wgstatsrecord',
            name='preshared_key',
            field=models.CharField(default='', max_length=44),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wgstatsrecord',
            name='previous_stat_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wgstatsrecord',
            name='stat_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wgstatsrecord',
            name='transfer_rx',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wgstatsrecord',
            name='transfer_rx_avg',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wgstatsrecord',
            name='transfer_rx_delta',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wgstatsrecord',
            name='transfer_tx',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wgstatsrecord',
            name='transfer_tx_avg',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wgstatsrecord',
            name='transfer_tx_delta',
            field=models.BigIntegerField(default=0),
        ),
    ]
