# Generated by Django 6.0 on 2025-12-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_wgstatsrecord_allowed_ips_wgstatsrecord_endpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wgstatsrecord',
            name='persistent_keepalive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wgclient',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
