# Generated by Django 6.0 on 2025-12-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_wgstatsrecord_persistent_keepalive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wgstatsrecord',
            name='previous_stat_time',
        ),
        migrations.AddField(
            model_name='wgstatsrecord',
            name='seconds_delta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wgstatsrecord',
            name='transfer_rx_avg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wgstatsrecord',
            name='transfer_tx_avg',
            field=models.IntegerField(default=0),
        ),
    ]
